### ISSUE TITLE
Scale issue

### ISSUE THREAD

**Issue by armaganwork** [hlefe/ar_flutter_plugin_flutterflow#1]
Hello, how to scale with 2 fingers? I  have checked out the ObjectManager class but could not find anything related.

**Comment by hlefe** [comment]
There's an example of the gestures you can apply to nodes here (in the original plugin):
https://github.com/CariusLars/ar_flutter_plugin/blob/main/example/lib/examples/objectgesturesexample.dart
Indeed, scaling is not managed, only panning or rotation. The ARNode has a scale parameter, maybe you can use it to update the value in another way.

**Comment by armaganwork** [comment]
Thanks
