### ISSUE TITLE
Object Placement on Ceiling Not Supported

### ISSUE THREAD

**Issue by jesulo** [hlefe/ar_flutter_plugin_flutterflow#14]
Object Placement on Ceiling Not Supported

Description
Currently, the ar_flutter_plugin_flutterflow does not support placing objects on the ceiling. It can detect horizontal planes facing downward, but it does not correctly recognize or handle planes for ceilings, and well as vertical planes.

Steps to Reproduce
Open an AR session using the ar_flutter_plugin_flutterflow.
Attempt to place an object on a detected ceiling plane.
Observe that the object is not placed or the ceiling plane is not recognized.
Expected Behavior
The plugin should recognize ceiling planes and allow objects to be placed on them.

Actual Behavior
Ceiling planes are not detected, and objects cannot be placed on ceilings.

**Comment by hlefe** [comment]
I don't think it's possible to detect ceilings at this stage, but if you have any ideas on how to achieve it, I'm all ears!
