### ISSUE TITLE
Namespace not specified in modules's build file. 

### ISSUE THREAD

**Issue by ireneelizabethsabu** [hlefe/ar_flutter_plugin_flutterflow#18]
Unable to build project after adding ar_flutter_plugin_flutterflow ( version 0.7.39 )

**ERROR:**

FAILURE: Build failed with an exception.

What went wrong:
A problem occurred configuring project ':ar_flutter_plugin_flutterflow'.
Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

 If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Error: Gradle task assembleDebug failed with exit code 1

---------------------------------------------------

**FLUTTER DOCTOR**

[✓] Flutter (Channel stable, 3.22.2, on macOS 15.1.1 24B91 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.95.3)
[✓] Connected device (4 available)

Could anyone please help to rectify this error ? 
Thanks.

**Comment by hlefe** [comment]
This issue was resolved in thie commit : 
https://github.com/hlefe/ar_flutter_plugin_flutterflow/commit/f09048cbf591d8508dfe5731c716d97e73615b27

Simply use the latest version of the plugin : 
ar_flutter_plugin_flutterflow: ^0.7.55
