### ISSUE TITLE
Not working in android emulator. 

### ISSUE THREAD

**Issue by yugeshpoudel45** [hlefe/ar_flutter_plugin_flutterflow#7]
![image](https://github.com/hlefe/ar_flutter_plugin_flutterflow/assets/104973762/123d667e-ae25-4a05-b503-04c121bba0e9)
This issue arises while trying to run it in android emulator in virtualscene. Can you help me with it?

**Comment by hlefe** [comment]
Hello, I think it will be challenging to get this plugin to work in an Android simulator; perhaps someone else can assist you with this.
