### ISSUE TITLE
Unable to load renderable

### ISSUE THREAD

**Issue by pejor76** [hlefe/ar_flutter_plugin_flutterflow#9]
When i am trying to show a 3d object that i have locally in my phone i get this errors
![image](https://github.com/hlefe/ar_flutter_plugin_flutterflow/assets/112394180/92191b5c-4921-46d0-891e-edf9feaf5a95)

**Comment by TravaMurava-jpg** [comment]
hey! have you fixed the issue?

**Comment by pejor76** [comment]
I wasnt able to fix this problem, so at the end i am simply downloading the 3d model before I use it

**Comment by pejor76** [comment]
I am using external urls for downloading the 3d model and then I am using the model that I just downloaded

**Comment by jesulo** [comment]
Is it possible update dependencies to  [sceneform-android](https://github.com/SceneView/sceneform-android)? it solve much rendering issues

**Comment by hlefe** [comment]
@pejor76 I've added an example with local and web files; maybe that will help you.
@jesulo I’d love for someone to help me do this; in the meantime, I recommend using Unity, which has fewer rendering issues, and then importing the project into Flutter using plugins like flutter_unity_widget.
